services:
  postflow-db:
    image: postgres:18-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postflow
      POSTGRES_DB: postflow
    volumes:
      - postflow-db-data:/var/lib/postgresql/data
      - ./init_scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postflow -d postflow"]
      interval: 10s
      timeout: 5s
      retries: 5

  s3:
    image: dxflrs/garage:v2.2.0
    container_name: postflow_s3
    restart: unless-stopped
    ports:
      # S3 API
      - 3900:3900
    volumes:
      - garage-meta:/var/lib/garage/meta
      - garage-data:/var/lib/garage/data
      - ./garage.dev.toml:/etc/garage.toml:ro

volumes:
  postflow-db-data:
  garage-meta:
  garage-data:
